"""Download the OCR files and page map for a Miñano volume.

Miñano's *Diccionario geográfico-estadístico de España y Portugal*
(1826-1829) has 11 volumes — 10 alphabetical (I-X) plus the Suplemento
(XI) — scanned by Google from various library partners and re-hosted on
Internet Archive under **heterogeneous identifiers**:

- Tomo XI (Suplemento, 1829, Complutense): ``diccionariogeog00bedogoog``
- ... (other tomos to be resolved as we expand beyond the supplement;
  see TODO below).

For each volume we need:

- ``_chocr.html.gz`` — compressed hOCR, paragraph-segmented. The
  ``id="page_LEAF"`` per page lets us recover which leaf each
  paragraph belongs to.
- ``_page_numbers.json`` — leaf→printed-page map.
- ``_djvu.txt`` — plain text. Kept for ad-hoc grep; the chOCR is the
  canonical input.

Run: ``python scripts/fetch_volume.py <vol>``  (e.g. ``11``)
"""
from __future__ import annotations

import sys
import urllib.request
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
DATA = PROJECT / "data"

UA = "Mozilla/5.0 (research)"

# Map Miñano tomo (01-11) → IA identifier. Filled in incrementally as
# we resolve each volume's source (different libraries digitised
# different copies, so identifiers don't follow a regular pattern).
VOL_TO_IDENTIFIER: dict[str, str] = {
    # All identifiers below have chocr.html.gz + page_numbers.json
    # available (verified 2026-05). The Toronto ``diccionariogeogr<NN>mi``
    # series is preferred where available — cleanest scans, consistent
    # numbering, ABBYY hOCR generated by IA.
    "01": "diccionariogeogr01mi",       # 1826, Univ. Toronto. A-AZ.
    "02": "diccionariogeogr02mi",       # 1826, Univ. Toronto. BAB-CAS. (PoC volume)
    "03": "diccionariogeogr03mi",       # 1826, Univ. Toronto. CAS-ESPADILLO.
    "04": "diccionariogeog01bedogoog",  # 1826, Complutense.   ESP-HIT.
    # Tomo V is *not* available with chocr on IA — see TOMOS_WITHOUT_CHOCR
    # below. Critical because MALLORCA/MENORCA/MAHON live here.
    "06": "diccionariogeog05machgoog",  # 1827, Google scan.   "TOMO VI" body.
    "07": "diccionariogeog07machgoog",  # 1827, Google scan.   "TOMO VII" body.
    "08": "diccionariogeog04bedogoog",  # 1827, Complutense.   SAN-TEM (486 p.).
    "09": "bub_gb_L1BIFQFZTHoC",        # 1828, Bayerische Staatsbibliothek.
                                         # TOR-VIL. Opaque BSB identifier — easy to miss
                                         # in IA search; spotted only via the
                                         # `creator:(Miñano)` scrape (80 hits).
    "11": "diccionariogeogr11mi",       # 1829, Univ. Toronto. Suplemento.
}


# Tomos for which IA serves no chocr.html.gz directly, but does serve
# the underlying ABBYY raw (``<identifier>_abbyy.gz``). Those are
# handled by ``scripts/derive_chocr_from_abbyy.py``, which downloads
# the ABBYY raw, runs IA's own ``abbyy-to-hocr`` tool to produce a
# structurally identical chocr, and runs ``hocr-pagenumbers`` for the
# leaf→printed-page map. Quality is identical to IA-served chocr (it's
# the same ABBYY output, just packaged differently).
ABBYY_DERIVED: dict[str, str] = {
    "05": "diccionariogeog06machgoog",   # 1826, "TOMO V" (HIT-MEMBRIVE).
                                          # Contains MALLORCA, MAHON, MAR, MARÍA, MENORCA.
    "10": "diccionariogeog02bedogoog",   # 1828, "TOMO X" — partial scan only
                                          # (~125 pages, no Z-words; Balearic
                                          # content nil).
}

# No tomos are entirely missing from IA — confirmed exhaustive 2026-05
# via `creator:(Miñano)` scrape (80 results). All 11 tomos exist in
# some form, and all 11 now have a chocr we can feed the pipeline
# (9 directly from IA, 2 derived locally from ABBYY).
TOMOS_MISSING: dict[str, str] = {}

SUFFIXES = {
    "chocr": ("_chocr.html.gz", DATA / "chocr", ".html.gz"),
    "page_numbers": ("_page_numbers.json", DATA / "page_numbers", ".json"),
    "txt_djvu": ("_djvu.txt", DATA / "txt_djvu", ".txt"),
}


def fetch(vol: str, kind: str) -> Path:
    identifier = VOL_TO_IDENTIFIER[vol]
    remote_suffix, out_dir, local_ext = SUFFIXES[kind]
    url = f"https://archive.org/download/{identifier}/{identifier}{remote_suffix}"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"tomo{vol}{local_ext}"
    if out.exists() and out.stat().st_size > 0:
        print(f"  [skip] {out.relative_to(PROJECT)} already exists")
        return out
    print(f"  [GET]  {url}")
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=600) as r:
        out.write_bytes(r.read())
    print(f"  [OK]   {out.relative_to(PROJECT)} ({out.stat().st_size/1024/1024:.1f} MB)")
    return out


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit("Usage: python scripts/fetch_volume.py <vol>  (e.g. 11)")
    vol = sys.argv[1].zfill(2)
    if vol in ABBYY_DERIVED:
        sys.exit(
            f"Tomo {vol} ({ABBYY_DERIVED[vol]}) ships no chocr.html.gz on IA. "
            f"Run instead: python scripts/derive_chocr_from_abbyy.py {vol}"
        )
    if vol not in VOL_TO_IDENTIFIER:
        known = ", ".join(sorted(VOL_TO_IDENTIFIER))
        sys.exit(f"Volume {vol} not yet mapped to an IA identifier. Known: {known}")
    print(f"=== Tomo {vol} ({VOL_TO_IDENTIFIER[vol]}) ===")
    for kind in SUFFIXES:
        fetch(vol, kind)


if __name__ == "__main__":
    main()
